### ISSUE TITLE
Allow usage of PR `edited` Event

### ISSUE THREAD

**Issue by Lapotor** [Namchee/conventional-pr#117]
Currently the [`edited`](https://docs.github.com/de/webhooks/webhook-events-and-payloads?actionType=edited#pull_request) Event is not supported by action.

When we don't support this event we would need to always push a commit or reopen a PR when we change the PR Title or description. So when we correct a PR after the action fails a simple change of the PR would not result in a new check against lint.

**Comment by Namchee** [comment]
@all-contributors please add @Lapotor for ideas
