### ISSUE TITLE
conventional-pr not working anymore with strict: false

### ISSUE THREAD

**Issue by smutel** [Namchee/conventional-pr#17]
Hello,

The conventional-pr is not working anymore on my project.
We can see that in this PR: https://github.com/smutel/terraform-provider-netbox/pull/41/checks, the user did'nt respect de conventional commits. However nothing appends in the MR except the pipeline has failed.

Recently I put the option `strict: false` but I am not sure that it it the root cause of this issue.
Thanks in advance.

**Comment by Namchee** [comment]
Hello, sorry for the (very) late response.

I don't think it's related with `strict: false`, but I'll investigate it tomorrow.

**Comment by Namchee** [comment]
Can't find anything wrong with the code and API responses. I think I'll test this using dummy accounts later

**Comment by chez14** [comment]
I made a quick test on #20, will this enough to help you check on things?

**Comment by Namchee** [comment]
@chez14 , sorry I messed up with the tokens. Could you please open a new PR?

**Comment by chez14** [comment]
Just sent you #21, it appears the PR unable to access the tokens, could you check whether the workflow settings are correct? Thanks!

**Comment by Namchee** [comment]
@smutel, there's a bug when this action tries to get a permission level, should be fixed #24. Could you please try it again with the newest version?

I'll temporarily close this, but feel free to re-open if the problem persists.

**Comment by smutel** [comment]
Sure. Thanks.

**Comment by smutel** [comment]
I don't know if it is the same problem or another one ...

But you can see here that it does not work ...
https://github.com/smutel/terraform-provider-netbox/pull/48/checks?check_run_id=2081991524
