### ISSUE TITLE
Improve message "Failed to close pull request"

### ISSUE THREAD

**Issue by smutel** [Namchee/conventional-pr#27]
Hello,

Currently when the check is not passing we have only the message: "Failed to close pull request".

But it could be due to several reason.

**Comment by smutel** [comment]
Even with the improvement, no message is displayed here: https://github.com/smutel/terraform-provider-netbox/runs/3645282370?check_suite_focus=true

**Comment by Namchee** [comment]
Noticed that too, seems like we can't use `log` for this. I've asked a question regarding the behavior [here](https://github.community/t/docker-container-action-doesnt-write-to-stdout/201916), feel free to track it.
