### ISSUE TITLE
snyk-bot is not whitelisted

### ISSUE THREAD

**Issue by BinToss** [Namchee/conventional-pr#64]
https://github.com/HaloSPV3/SPV3.Loader/pull/101
![image](https://user-images.githubusercontent.com/7243190/152307120-db358f77-d7a7-43e3-b215-9622e5e8bdbf.png)

## Why?
snyk-bot is an automated user account instead of a GitHub Bot. It will need to be manually whitelisted until the Snyk organization uses a GitHub Bot.

**Comment by Namchee** [comment]
Thanks for filling an issue.

Yeah, this is caused by the nature of the account itself, which is not a bot account. A possible fix I can think of is to allow account whitelisting. I'm open to better ideas though.

**Comment by BinToss** [comment]
The only alternative I can think of is whitelisting with a string.Contains("bot") filter, but that would lead to false-positives. 

So, whitelisting specific accounts would be preferred. I hope the account whitelist wont need to be updated frequently.

**Comment by Namchee** [comment]
@BinToss , you can try v0.9.0 now. For the input, try adding `ignored_users: snyk-bot`

**Comment by BinToss** [comment]
Sorry for the late response. Confirmed it working the other day. It took me a while to circle back to ci work.
