### ISSUE TITLE
feat: add ability to edit existing comment

### ISSUE THREAD

**Issue by Namchee** [Namchee/conventional-pr#76]
## Overview

Currently, any changes in a pull request that needs re-validation are reported in form of a new comment. This might be a good option for small repositories that don't have too many activities. However, this is impractical on big repositories that might change the pull request state often as it might clutter the pull request itself.

Add an option to toggle editing instead of publishing new report.

**Comment by Chrisjainsley** [comment]
Currently looking at a PR by the renovate bot that has about 20 reports so this is very much needed for cleaner PR pages. I would think this should be the default behaviour.
