### ISSUE TITLE
feat: Less verbose comment on valid PR

### ISSUE THREAD

**Issue by avorima** [Namchee/conventional-pr#78]
The default config generates a lot of noise even when the PR validation succeeded. I would expect the default behavior to be silent on success and noisy on failure. Optionally, e.g. for debugging, the current verbose report style could be used.

This may also be exacerbated by https://github.com/Namchee/conventional-pr/issues/76.

As a way to circumvent this, I'm using `report: false` and `template: '...'`. That way I only get a comment when the checks fail, but on the other hand no new comment is added when the issues were fixed.

**Comment by Namchee** [comment]
@avorima Thanks for showing an interest in this project!

Thinking about your use case, future versions will have `report` set to `false` by default to avoid a lot of noise (as `edit` has its own caveats). As for `template`, it shouldn't be generated by default, as `template` is an extra message that will be posted whenever a pull request is invalid.

I don't think #76 will exacerbate the problem. If #77 is merged, you'll only see one pull request comment whenever a pull request validation is executed. That way, it'll generate much lesser noise.

**Comment by avorima** [comment]
But the issue with `report: false` is that it forces me to use `template` to get some kind of comment on my PR. I want the verbose report, just only when there's actually something wrong.
As a side note, `template` might be a bit of a misnomer because it doesn't really process the text and just passes it on to the REST API.

**Comment by Namchee** [comment]
I see where you're going. Unfortunately, that's the only way you'll get the desired behavior at the moment.

For the `template` option, I plan to change the option name in future releases. As you've guessed, I've changed the behavior of the `template` option compared to old releases.

For less verbosity, I think I can create the `verbose` option so `conventional-pr` only posts a comment whenever the validation fails. Does it sound good enough for you?

**Comment by avorima** [comment]
Yes, that would be great!
