### ISSUE TITLE
hardcoded API url leads to bad credentials error on GitHub Enterprise server

### ISSUE THREAD

**Issue by Th3S4mur41** [Namchee/conventional-pr#90]
Running the conventional-pr action on an on premise GitHub Enterprise server results in a bad crendentials error.
The error is misleading though and results from the fact that the action is trying to fetch the pull request data from github.com instead of the actual GitHub server.

```
Run Namchee/conventional-pr@v0.13.0
2023/09/06 06:23:14 [INFO] Initializing conventional-pr
2023/09/06 06:23:14 [INFO] Reading configuration from environment variables
2023/09/06 06:23:14 [INFO] Reading repository metadata
2023/09/06 06:23:14 [INFO] Initializing GitHub Client
2023/09/06 06:23:14 [INFO] Reading pull request metadata
2023/09/06 06:23:14 [INFO] Validating pull request sub-events
Error: /06 06:23:14 [ERROR] Failed to fetch pull request data: GET https://api.github.com/repos/***/***/pulls/20: 401 Bad credentials []
```

All references to `https://api.github.com` should be replaced through `${{github.api_url}}` to allow the action to work on Enterprise server

**Comment by Namchee** [comment]
Thanks for filing an issue!

I never used this for Enterprise accounts, so I didn't know that this issue exists. I'll see what I can do.

**Comment by Namchee** [comment]
@Th3S4mur41, I have merged potential fix for this on #91, could you please try to use the master branch version of `conventional-pr` and see if it fixed the issue? I'll release a new version as soon as this issue has been confirmed to be fixed.

To use the master branch version, please change the action version in the workflow file to `@master`

```yaml
- name: Check PR semantics
  uses: Namchee/conventional-pr@master
```

**Comment by userjoergjakoby** [comment]
With Namchee/conventional-pr@master we don't have the mentioned error anymore

**Comment by Namchee** [comment]
Thanks for confirming! WIll release a new version soon

**Comment by Namchee** [comment]
@all-contributors please add @Th3S4mur41 for bug
